### ISSUE TITLE
dichotomization of non-binary treatments

### ISSUE THREAD

**Issue by josherrickson** [benbhansen-stats/propertee#30]
There's some scattered discussion of this in #21 and #18, moving into its own issue.

We need a way for users to identify a binary comparison of treatment groups at the point in time when weights are created. First question: Should this dichomization take place within the weight calculation (e.g. `ate(des, txtgroup = 3)`) or should it be a characteristic of `Design`s with non-binary treatment (e.g. `des <- RCT_Design(factor ~ ....); desbin <- make_binary_treatment(des, txtgroup = 2)`, or just require it as an argument to the `Design` creation whenever the outcome has >2 levels).

- Making this a `Design` attribute would be useful for scenarios where a user has some larger study, but for the particular analysis only cares about one specific comparison. 
- Additionally, putting in `Design` keeps the simplicity of `ate(des)` in most scenarios (ignoring `by` complications for the moment).
- On the other hand, making it an argument to the weight functions would allow more flexibility and remove the need for users making a lot of different pairwise comparisons to create many copies of the `Design` with different dichotomization.

The question comes down to whats more likely to be the common scenario: A user who has one pairwise comparison in an otherwise multi-treatment data set, or a user who carries out lots of different pairwise comparisons.

(Of course, perhaps the answer is both; an optional way to specify in a `Design` the pairwise comparison of interest, and if that is `NULL`, requiring it in the weights call.)

Supplemental question: Are we assuming that all comparisons are treatment level X versus all other levels, or might we compare level X vs level Y, ignoring other levels? And if we do the latter, do we need to keep them in the `Design` for weighting purposes, or can we just encourage users in that scenario to create a `Design` with only data from treatment levels X and Y?

**Comment by jwasserman2** [comment]
On the `i30_dichotomization` branch, I've updated the codebase to handle the cases Josh E and Ben have outlined above (written explicitly in `test.dichotomy_args.R`) and to pass the tests Ben wrote earlier (I made a couple small corrections, and additionally a couple small edits related to question 1 below. Also @benthestatistician, `lmitt()` doesn't allow for explicit calls to `a.()`, if that's something you want to revisit with your `lmitt()` example in the May 13 proposal). Otherwise, I have two outstanding questions:
1. Do we want `WeightedDesign` objects to have a `dichotomy` slot? The only advantage I see it providing is that users don't have to enter the `dichotomy` argument in `lmitt()` if they create weights the way Ben has in his May 13 proposal. If `WeightedDesign` objects don't store `dichotomy`, then `c()` can return a `WeightedDesign` rather than `numeric`--thereby maintaining the `Design` information--while still assuaging Ben's concern in his previous comment about conflicting dichotomies. My code on the branch does this, so I made edits to Ben's tests where he originally expected a `numeric` output. However, if we would rather the `numeric` output that strips the `Design` information, I can change it.
2. Do we want `teeMod` objects to store `dichotomy`? I don't see it being necessary for any downstream tasks that we accommodate, and if a user needed to remember what their dichotomization was they could check the `call`, but I wanted to float the idea to others. 

You all can pull the changes I've made to this branch and play around with things. I think I'll also want to make another pass and see if there are any unnecessary functions that I've written or if the code could be streamlined further.

**Comment by benthestatistician** [comment]
Thanks! 
I think my preferences are to 
a. retain the `dichotomy` slot in the WeightedDesign class;
b. drop design info when combining WDs (ie c(WD, WD) -> numeric). 

I wind up with (a) thinking about the user who decides to run separate regressions for each of several dichotomies, then stitch the results together in some way.  (In the six schools toy example appearing in our "Combine WeightedDesigns & align weights...", this would mean estimating AY20 and AY21 effects in separate regressions.) In these cases, a user would reasonably expect things to work as usual after passing her dichotomy in to `ett()` or another weight-making function.  I.e., a dichotomy passed to `ate()` would also have to be available to the `assigned()` in a surrounding `lm()` call, or to a surrounding `lmitt()` call, in order to set the treatment variable from the design.  I take this to mean we'd need the WD class to retain its `dichotomy=` slot.

Re (b), I remain worried that I we don't have oversight over the varying ways users might think to combine weights derived from a design.  Lacking that, it seems safest not to assume that our hidden structure underneath the overt weights would have the meaning we'd mean for it to have.  I.e., seems safer to return a flat numeric.  For someone using this workflow, it doesn't seem too much to ask to have them pass their design explicitly to `lmitt()` or `assigned()`. 


In other news, I've updated my May 13 proposal as you suggest just above, @jwasserman2; thanks.  Also, please don't hesitate to edit my code or tests, e.g. in `test.CombinedWeightedDesign.R`.  There you've commented out some things of mine that might simply have been removed or fixed. No need to be shy about changing or removing my stuff!
